WITH source_data AS (

    SELECT *
    FROM {{ source('raw', 'CUSTOMERS') }}

),

cleaned_data AS (

    SELECT
        CUSTOMER_ID,
        UPPER(TRIM(FIRST_NAME)) AS FIRST_NAME,
        UPPER(TRIM(LAST_NAME)) AS LAST_NAME,
        UPPER(TRIM(GENDER)) AS GENDER,
        AGE,
        LOWER(TRIM(EMAIL)) AS EMAIL,
        TRIM(PHONE) AS PHONE,
        UPPER(TRIM(CITY)) AS CITY,
        UPPER(TRIM(STATE)) AS STATE,
        UPPER(TRIM(COUNTRY)) AS COUNTRY,
        REGISTRATION_DATE,
        UPPER(TRIM(CUSTOMER_SEGMENT)) AS CUSTOMER_SEGMENT,
        UPPER(TRIM(LOYALTY_TIER)) AS LOYALTY_TIER
    FROM source_data

)

SELECT *
FROM cleaned_data
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CUSTOMER_ID
    ORDER BY REGISTRATION_DATE DESC
) = 1