WITH source_data AS (

    SELECT *
    FROM {{ source('raw', 'WEBSITE_SESSIONS') }}

),

cleaned_data AS (

    SELECT
        SESSION_ID,
        CUSTOMER_ID,
        SESSION_START,
        SESSION_END,
        UPPER(TRIM(DEVICE)) AS DEVICE,
        UPPER(TRIM(BROWSER)) AS BROWSER,
        UPPER(TRIM(OPERATING_SYSTEM)) AS OPERATING_SYSTEM,
        UPPER(TRIM(TRAFFIC_SOURCE)) AS TRAFFIC_SOURCE,
        UPPER(TRIM(LANDING_PAGE)) AS LANDING_PAGE,
        PAGES_VIEWED,
        SESSION_DURATION_SECONDS,
        IS_LOGGED_IN
    FROM source_data

)

SELECT *
FROM cleaned_data
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY SESSION_ID
    ORDER BY SESSION_START DESC
) = 1