WITH customers AS (

    SELECT
        COUNT(*) AS TOTAL_ROWS,
        COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
        COUNT_IF(CUSTOMER_ID IS NULL) AS NULL_CUSTOMER_IDS
    FROM {{ ref('stg_customers') }}

),

orders AS (

    SELECT
        COUNT(*) AS TOTAL_ROWS,
        COUNT(DISTINCT ORDER_ID) AS UNIQUE_ORDERS,
        COUNT_IF(ORDER_ID IS NULL) AS NULL_ORDER_IDS,
        COUNT_IF(CUSTOMER_ID IS NULL) AS NULL_CUSTOMER_IDS
    FROM {{ ref('stg_orders') }}

),

order_items AS (

    SELECT
        COUNT(*) AS TOTAL_ROWS,
        COUNT(DISTINCT ORDER_ITEM_ID) AS UNIQUE_ORDER_ITEMS,
        COUNT_IF(ORDER_ITEM_ID IS NULL) AS NULL_ORDER_ITEM_IDS,
        COUNT_IF(QUANTITY IS NULL) AS NULL_QUANTITY,
        COUNT_IF(LINE_AMOUNT < 0) AS NEGATIVE_LINE_AMOUNT,
        COUNT_IF(LINE_AMOUNT IS NULL) AS NULL_LINE_AMOUNT
    FROM {{ ref('stg_order_items') }}

),

products AS (

    SELECT
        COUNT(*) AS TOTAL_ROWS,
        COUNT(DISTINCT PRODUCT_ID) AS UNIQUE_PRODUCTS,
        COUNT_IF(PRODUCT_ID IS NULL) AS NULL_PRODUCT_IDS
    FROM {{ ref('stg_products') }}

),

sessions AS (

    SELECT
        COUNT(*) AS TOTAL_ROWS,
        COUNT(DISTINCT SESSION_ID) AS UNIQUE_SESSIONS,
        COUNT_IF(SESSION_ID IS NULL) AS NULL_SESSION_IDS
    FROM {{ ref('stg_website_sessions') }}

)

SELECT
    CURRENT_TIMESTAMP() AS CHECK_TIMESTAMP,

    c.TOTAL_ROWS AS CUSTOMER_ROWS,
    c.UNIQUE_CUSTOMERS,
    c.NULL_CUSTOMER_IDS,

    o.TOTAL_ROWS AS ORDER_ROWS,
    o.UNIQUE_ORDERS,
    o.NULL_ORDER_IDS,
    o.NULL_CUSTOMER_IDS AS ORDER_NULL_CUSTOMER_IDS,

    oi.TOTAL_ROWS AS ORDER_ITEM_ROWS,
    oi.UNIQUE_ORDER_ITEMS,
    oi.NULL_ORDER_ITEM_IDS,
    oi.NULL_QUANTITY,
    oi.NEGATIVE_LINE_AMOUNT,
    oi.NULL_LINE_AMOUNT,

    p.TOTAL_ROWS AS PRODUCT_ROWS,
    p.UNIQUE_PRODUCTS,
    p.NULL_PRODUCT_IDS,

    s.TOTAL_ROWS AS SESSION_ROWS,
    s.UNIQUE_SESSIONS,
    s.NULL_SESSION_IDS

FROM customers c
CROSS JOIN orders o
CROSS JOIN order_items oi
CROSS JOIN products p
CROSS JOIN sessions s